- name: Create SSL certificate directory
  ansible.builtin.file:
    path: "{{ ssl_cert_dir }}"
    state: directory
    mode: '0755'

- name: Create SSL certificate
  ansible.builtin.copy:
    src: "{{ cluster_ssl_certificate }}"
    dest: "{{ ssl_cert_dir }}/fullchain.pem"
    mode: '0644'
    force: true

- name: Create SSL certificate key
  ansible.builtin.copy:
    src: "{{ cluster_ssl_certificate_key }}"
    dest: "{{ ssl_cert_dir }}/privkey.pem"
    mode: '0644'
    force: true