- name: restart pveproxy
  become: true
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: restart networking
  become: true
  ansible.builtin.service:
    name: pvenetcommit
    state: restarted