- name: Gather existing interfaces
  ansible.builtin.shell: pvesh get "/nodes/{{ inventory_hostname_short }}/network" --noborder --output-format json
  register: pve_interfaces_raw
  changed_when: false

- name: Set pve_interfaces as a list of interfaces
  ansible.builtin.set_fact:
    pve_interfaces: "{{ pve_interfaces_raw.stdout | from_json | json_query('[*].iface') }}"
  changed_when: false

- name: Add network interfaces
  ansible.builtin.shell: >
    pvesh create "/nodes/{{ inventory_hostname_short }}/network"
    --iface "{{ item.key }}"
    --type "{{ item.value.type }}"
    --cidr "{{ item.value.cidr }}"
    --bridge_ports "{{ item.value.bridge_ports }}"
    --autostart "{{ item.value.autostart }}"
  with_dict: "{{ proxmox_interfaces }}"
  when: "item.key not in pve_interfaces"
  notify:
    - restart networking

- name: Update network interfaces
  ansible.builtin.shell: >
    pvesh set "/nodes/{{ inventory_hostname_short }}/network/{{ item.key }}"
    --type "{{ item.value.type }}"
    --cidr "{{ item.value.cidr }}"
    --bridge_ports "{{ item.value.bridge_ports }}"
    --autostart "{{ item.value.autostart }}"
  with_dict: "{{ proxmox_interfaces }}"
  when: "item.key in pve_interfaces"
  notify:
    - restart networking