- name: Ensure libguestfs-tools are available
  become: true
  ansible.builtin.apt:
    state: present
    package:
      - libguestfs-tools

- name: Gathering existing VMs
  ansible.builtin.shell: qm list | awk 'NR>1 {print $2}'
  register: pve_vms
  changed_when: false
  tags: [ cloudinit-templates ]

- name: Remove existing Cloud-Init templates
  ansible.builtin.shell: "qm destroy $(qm list | awk '/{{ item.key }}/ {print $1}') --destroy-unreferenced-disk --purge"
  with_dict: "{{ proxmox_kvm }}"
  when: "proxmox_kvm | length > 0 and item.key in pve_vms.stdout_lines" # Only remove existing VMs
  tags: [ never, rebuild, cloudinit-templates ]

- name: Download Cloud-Init images
  ansible.builtin.get_url:
    url: "{{ item.value.cloudimg_url | default(proxmox_kvm_defaults.cloudimg_url) }}"
    dest: "/home/ansible/{{ item.value.cloudimg | default(proxmox_kvm_defaults.cloudimg) }}"
    checksum: "{{ item.value.cloudimg_checksum | default(proxmox_kvm_defaults.cloudimg_checksum) }}"
  with_dict: "{{ proxmox_kvm }}"
  when: "proxmox_kvm | length > 0"
  tags: [ cloudinit-templates ]

- name: Ensure QEMU Guest Agent in Cloud-Init images
  ansible.builtin.shell: |
    virt-customize -a /home/ansible/{{ item.value.cloudimg | default(proxmox_kvm_defaults.cloudimg) }} --install qemu-guest-agent,python3
    virt-customize -a /home/ansible/{{ item.value.cloudimg | default(proxmox_kvm_defaults.cloudimg) }} --truncate /etc/machine-id
  with_dict: "{{ proxmox_kvm }}"
  when: "proxmox_kvm | length > 0"
  tags: [ cloudinit-templates ]

- name: Prepare Cloud-Init templates
  ansible.builtin.shell: >
    VMID="{{ item.value.vmid | default('$(pvesh get /cluster/nextid)') }}";

    qm create $VMID
    --name "{{ item.key }}"
    --scsi0 "{{ item.value.storage | default(proxmox_kvm_defaults.storage) }}":0,import-from=/home/ansible/"{{ item.value.cloudimg | default(proxmox_kvm_defaults.cloudimg) }}",discard=on,iothread=1
    --ide2 "{{ item.value.storage | default(proxmox_kvm_defaults.storage) }}":cloudinit
    --ostype l26
    --scsihw virtio-scsi-single
    --serial0 socket
    --vga serial0
    --boot order=scsi0
    --agent 1
    --ciuser "{{ item.value.ciuser | default(proxmox_kvm_defaults.ciuser | default(omit)) }}"
    --cipassword "{{ item.value.cipassword | default(proxmox_kvm_defaults.cipassword | default(omit)) }}"
    --sshkeys "{{ item.value.sshkeys | default(proxmox_kvm_defaults.sshkeys | default(omit)) }}"
    --cpu x86-64-v2-AES
    --cores "{{ item.value.cores | default(proxmox_kvm_defaults.cores | default(omit)) }}"
    --memory "{{ item.value.memory | default(proxmox_kvm_defaults.memory | default(omit)) }}"
    --net0 virtio,bridge=vmbr0,firewall=1
    --ipconfig0 ip=dhcp

    qm template $VMID
  with_dict: "{{ proxmox_kvm }}"
  when: "proxmox_kvm | length > 0 and item.key not in pve_vms.stdout_lines" # Only create new VMs
  tags: [ cloudinit-templates ]