- name: Gathering existing LXC templates
  ansible.builtin.shell: pveam list local | awk 'NR>1 {gsub(/.*\//, "", $1); print $1}'
  register: lxc_templates_raw
  changed_when: false

- name: Set lxc_templates as a list of LXC template names
  ansible.builtin.set_fact:
    lxc_templates: "{{ lxc_templates_raw.stdout_lines }}"
  changed_when: false

- name: Remove LXC templates we are no longer using
  ansible.builtin.shell: "pveam remove local:vztmpl/{{ item }}"
  loop: "{{ lxc_templates | difference(proxmox_lxc) }}"
  when: item not in proxmox_lxc

- name: Download LXC templates
  ansible.builtin.shell: "pveam download local {{ item }}"
  loop: "{{ proxmox_lxc }}"
  when: item not in lxc_templates