- import_tasks: no-subscription.yml
  become: true

- import_tasks: interfaces.yml
  become: true
  when: "proxmox_interfaces | length > 0"
  tags: [ interfaces ]

- import_tasks: firewall.yml
  become: true

- import_tasks: terraform.yml
  become: true

- import_tasks: kvm.yml
  become: true
  when: "proxmox_kvm | length > 0"
  tags: [ never, kvm ]
