- import_tasks: no-subscription.yml
  become: true

- import_tasks: passthrough.yml
  become: true
  tags: [ never, passthrough ]

- import_tasks: terraform.yml
  become: true

- import_tasks: kvm.yml
  become: true
  when: "proxmox_kvm | length > 0"
  tags: [ never, kvm ]