domain: "jrtashjian.com"
domain_internal: "int.{{ domain }}"
authelia_fqdn: "sso.{{ domain }}"

cluster_ssl_certificate: "{{ inventory_dir }}/files/fullchain.pem"
cluster_ssl_certificate_key: "{{ inventory_dir }}/files/privkey.pem"