onepassword_vault: homelab

domain: "jrtashjian.com"
domain_internal: "int.{{ domain }}"
authelia_fqdn: "sso.{{ domain }}"

cluster_ssl_certificate: "{{ lookup('file', '../files/fullchain.pem') }}"
cluster_ssl_certificate_key: "{{ lookup('file', '../files/privkey.pem') }}"