- import_tasks: required.yml
  become: true

- import_tasks: papermc.yml
  become: true

- import_tasks: service.yml
  become: true

- name: Set appropriate ownership for Minecraft directory
  become: true
  ansible.builtin.file:
    path: /opt/minecraft
    state: directory
    recurse: yes
    owner: minecraft
    group: minecraft
    mode: '0755'
  tags:
    - permissions

- name: Enable and start minecraft service
  become: true
  ansible.builtin.service:
    name: minecraft
    enabled: yes
    state: started
  when: not ansible_check_mode
  tags:
    - software_update
    - config_update
