# Directory Structure
- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/minecraft/config
    - /opt/minecraft/plugins
  tags:
    - permissions

# Server Software
- name: Determine latest PaperMC build
  ansible.builtin.uri:
    url: https://api.papermc.io/v2/projects/paper/versions/1.21.5/builds
  register: request_papermc
  failed_when: request_papermc.status != 200
  retries: 3
  delay: 5
  tags:
    - software_update

- name: Stop minecraft service before updating files (if running)
  become: true
  ansible.builtin.service:
    name: minecraft
    state: stopped
  ignore_errors: yes
  tags:
    - software_update

- name: Download server and plugin files
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    force: yes
  loop:
    - { url: "https://api.papermc.io/v2/projects/paper/versions/{{ request_papermc.json.version }}/builds/{{ request_papermc.json.builds[-1].build }}/downloads/{{ request_papermc.json.builds[-1].downloads.application.name }}", dest: /opt/minecraft/paper.jar }
  notify: restart minecraft
  when: not ansible_check_mode
  register: download_result
  retries: 3
  delay: 5
  until: download_result is success
  tags:
    - software_update

- name: Update eula.txt
  ansible.builtin.ini_file:
    path: /opt/minecraft/eula.txt
    section: null
    option: "eula"
    value: "{{ eula_accept }}"
    no_extra_spaces: yes

- name: Copy server.properties
  ansible.builtin.copy:
    src: files/opt/minecraft/server.properties
    dest: /opt/minecraft/server.properties

- name: Override server.properties config for host
  ansible.builtin.ini_file:
    path: /opt/minecraft/server.properties
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  with_dict: "{{ server_properties_defaults | combine(server_properties, recursive=True) }}"
  when: "server_properties | length > 0"
  notify: restart minecraft
  tags:
    - config_update

- name: Update player permissions
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content | to_json }}"
  loop:
    - { dest: /opt/minecraft/ops.json, content: "{{ ops }}" }
    # - { dest: /opt/minecraft/whitelist.json, content: "{{ whitelist }}" }
    # - { dest: /opt/minecraft/banned-ips.json, content: "{{ banned_ips }}" }
    # - { dest: /opt/minecraft/banned-players.json, content: "{{ banned_players }}" }
  notify: restart minecraft
  tags:
    - config_update

- name: Update *.yml configuration
  ansible.builtin.copy:
    dest: "/opt/minecraft/{{ item.path }}"
    content: "{{ lookup('file', 'opt/minecraft/' + item.path) | from_yaml | combine(vars[item.key + '_defaults'], recursive=True) | combine(vars[item.key], recursive=True) | to_nice_yaml }}"
  loop:
    - { key: "paper_global", path: "config/paper-global.yml" }
    - { key: "paper_world", path: "config/paper-world-defaults.yml" }
    - { key: "bukkit", path: "bukkit.yml" }
    - { key: "spigot", path: "spigot.yml" }
    - { key: "commands", path: "commands.yml" }
  notify: restart minecraft
  tags:
    - config_update