- name: install minecraft server requirements
  ansible.builtin.apt:
    state: present
    package:
      - git
      - build-essential
      - openjdk-17-jre-headless
    update_cache: true

- name: add the user 'minecraft'
  ansible.builtin.user:
    name: minecraft
    system: yes
    home: /opt/minecraft
    shell: /bin/bash
