# Install JDK with https://docs.papermc.io/misc/java-install#ubuntudebian

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required tools
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gnupg
      - wget
      - git
      - build-essential
    state: present

- name: Add GPG key for Corretto repository
  ansible.builtin.apt_key:
    url: https://apt.corretto.aws/corretto.key
    state: present

- name: Add Corretto repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.corretto.aws stable main
    state: present
    update_cache: true

- name: Update apt cache after adding Corretto repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java 21 and dependencies
  ansible.builtin.apt:
    name:
      - java-21-amazon-corretto-jdk
      - libxi6
      - libxtst6
      - libxrender1
    state: present

- name: add the user 'minecraft'
  ansible.builtin.user:
    name: minecraft
    system: yes
    home: /opt/minecraft
    shell: /bin/bash
