# Install JDK with https://docs.papermc.io/misc/java-install#ubuntudebian

- name: Add GPG key for Corretto repository
  ansible.builtin.apt_key:
    url: https://apt.corretto.aws/corretto.key
    state: present

- name: Add Corretto repository
  ansible.builtin.apt_repository:
    repo: deb https://apt.corretto.aws stable main
    state: present
    update_cache: true

- name: Install Minecraft server dependencies
  ansible.builtin.apt:
    state: present
    update_cache: yes
    package:
      - ca-certificates
      - apt-transport-https
      - gnupg
      - wget
      - git
      - build-essential
      - java-21-amazon-corretto-jdk
      - libxi6
      - libxtst6
      - libxrender1

- name: Create Minecraft system user
  ansible.builtin.user:
    name: minecraft
    system: yes
    home: /opt/minecraft
    shell: /bin/bash
