minecraft_servers:
  lobby: "minecraft-lobby.int.jrtashjian.com:25565"
  survival: "minecraft-main.int.jrtashjian.com:25565"
  hardcore: "minecraft-hardcore.int.jrtashjian.com:25565"
  creative: "minecraft-creative.int.jrtashjian.com:25565"