minecraft_servers: |
  {% set servers = {} %}
  {% for world in groups['minecraft-worlds'] %}
  {% set index = world.split('.')[0].replace('minecraft-', '') %}
  {% if index == "main" %}
  {% set index = "survival" %}
  {% endif %}
  {% set servers = servers.update({index: world + ":25565"}) %}
  {% endfor %}
  {{ servers }}