config_yml:
  groups:
    jrtashjian:
      - admin
  ip_forward: true
  listeners:
    - force_default_server: true
      forced_hosts:
        lobby: lobby
      host: 0.0.0.0:25565
      max_players: 15
      motd: Talos Server
      query_port: 25565
  log_pings: false
  online_mode: false
  permissions:
    admin:
      - bungeecord.command.alert
      - bungeecord.command.end
      - bungeecord.command.ip
      - bungeecord.command.reload
    default:
      - bungeecord.command.server
      - bungeecord.command.list
      - floodgate.command.linkaccount
      - floodgate.command.unlinkaccount
  servers:
    creative:
      address: minecraft-creative.int.jrtashjian.com:25565
      motd: Creative Server
      restricted: false
    hardcore:
      address: minecraft-hardcore.int.jrtashjian.com:25565
      motd: Hardcore Server
      restricted: false
    lobby:
      address: minecraft-lobby.int.jrtashjian.com:25565
      motd: Server Lobby
      restricted: false
    survival:
      address: minecraft-main.int.jrtashjian.com:25565
      motd: Survival Server
      restricted: false

velocity:
  online-mode: "false"
  show-max-players: 15

velocity_servers:
  lobby: "minecraft-lobby.int.jrtashjian.com:25565"
  survival: "minecraft-main.int.jrtashjian.com:25565"
  hardcore: "minecraft-hardcore.int.jrtashjian.com:25565"
  creative: "minecraft-creative.int.jrtashjian.com:25565"