- name: install minecraft server requirements
  become: true
  apt:
    state: present
    update_cache: yes
    package:
      - git
      - build-essential
      - openjdk-17-jre-headless

- name: add the user 'minecraft'
  become: true
  ansible.builtin.user:
    name: minecraft
    system: yes
    home: /opt/minecraft
    shell: /bin/bash

- name: create plugins directory
  become: true
  ansible.builtin.file:
    path: /opt/minecraft/plugins
    state: directory

- name: create plugins/floodgate directory
  become: true
  ansible.builtin.file:
    path: /opt/minecraft/plugins/floodgate
    state: directory

# https://papermc.io/software/velocity
- name: Determine latest Velocity build
  uri:
    url: https://api.papermc.io/v2/projects/velocity/version_group/3.0.0/builds
  register: request_velocity

- name: Stop minecraft-proxy service
  become: true
  ansible.builtin.service:
    name: minecraft-proxy
    state: stopped
  ignore_errors: yes
  tags: reconfigure

- name: Download server files
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - {
        url: "https://api.papermc.io/v2/projects/velocity/versions/{{ request_velocity.json.builds[-1].version }}/builds/{{ request_velocity.json.builds[-1].build }}/downloads/{{ request_velocity.json.builds[-1].downloads.application.name }}",
        dest: /opt/minecraft/velocity.jar,
      }
    - {
        # https://geysermc.org/download?project=geyser
        url: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/velocity",
        dest: /opt/minecraft/plugins/Geyser.jar,
      }
    - {
        # https://geysermc.org/download?project=floodgate
        url: "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/velocity",
        dest: /opt/minecraft/plugins/floodgate.jar,
      }
    - {
        url: "https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/fix-weird-via-issue/lastSuccessfulBuild/artifact/database/sqlite/build/libs/floodgate-sqlite-database.jar",
        dest: /opt/minecraft/plugins/floodgate/floodgate-sqlite-database.jar,
      }
    - {
        # https://github.com/sekwah41/Advanced-Portals
        url: "https://cdn.modrinth.com/data/axTqSWQA/versions/I8wYnsdu/Advanced-Portals-Spigot-2.5.0.jar",
        dest: /opt/minecraft/plugins/Advanced-Portals.jar,
      }
  notify: restart minecraft-proxy
  when: not ansible_check_mode

- name: Update *.toml configuration
  ansible.builtin.copy:
    dest: "/opt/minecraft/{{ item.path }}"
    content: "{{ lookup('file', 'opt/minecraft/' + item.path) }}"
  loop:
    - { key: "velocity_toml", path: "velocity.toml" }
  notify: restart minecraft-proxy

- name: Remove sections in velocity.toml
  ansible.builtin.ini_file:
    path: /opt/minecraft/velocity.toml
    section: "{{ item }}"
    state: absent
  loop:
    - servers
    - forced-hosts

- name: Update velocity.toml
  ansible.builtin.ini_file:
    path: /opt/minecraft/velocity.toml
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ velocity }}"
  when: "velocity | length > 0"

- name: Update servers section in velocity.toml
  ansible.builtin.ini_file:
    path: /opt/minecraft/velocity.toml
    section: servers
    option: "{{ item.key }}"
    value: "\"{{ item.value }}\""
    state: present
  with_dict: "{{ velocity_servers }}"
  when: "velocity_servers | length > 0"

- name: Add 'try' option to servers section in velocity.toml
  ansible.builtin.ini_file:
    path: /opt/minecraft/velocity.toml
    section: servers
    option: "try"
    value: "[\"{{ velocity_servers.keys() | list | first }}\"]"
    state: present
  when: "velocity_servers | length > 0"

- name: Re-add forced-hosts in velocity.toml
  ansible.builtin.ini_file:
    path: /opt/minecraft/velocity.toml
    section: forced-hosts
    allow_no_value: true
    state: present

- name: Create service
  become: true
  template:
    src: etc/systemd/system/minecraft-proxy.service.j2
    dest: /etc/systemd/system/minecraft-proxy.service
    owner: root
    group: root
  notify: start minecraft-proxy

- name: give 'minecraft' user ownership
  become: true
  ansible.builtin.file:
    path: /opt/minecraft
    state: directory
    recurse: yes
    owner: minecraft
    group: minecraft