jvm_memory: "1G"

# Aikar's JVM Startup Flags
# https://docs.papermc.io/paper/aikars-flags
aikar_jvm_flags:
  - "-XX:+UseG1GC"
  - "-XX:+ParallelRefProcEnabled"
  - "-XX:MaxGCPauseMillis=200"
  - "-XX:+UnlockExperimentalVMOptions"
  - "-XX:+DisableExplicitGC"
  - "-XX:+AlwaysPreTouch"
  - "-XX:G1NewSizePercent=30"
  - "-XX:G1MaxNewSizePercent=40"
  - "-XX:G1HeapRegionSize=8M"
  - "-XX:G1ReservePercent=20"
  - "-XX:G1HeapWastePercent=5"
  - "-XX:G1MixedGCCountTarget=4"
  - "-XX:InitiatingHeapOccupancyPercent=15"
  - "-XX:G1MixedGCLiveThresholdPercent=90"
  - "-XX:G1RSetUpdatingPauseTimePercent=5"
  - "-XX:SurvivorRatio=32"
  - "-XX:+PerfDisableSharedMem"
  - "-XX:MaxTenuringThreshold=1"
  - "-Dusing.aikars.flags=https://mcflags.emc.gs"
  - "-Daikars.new.flags=true"

# Example item:
# - option: "pvp"
#   value: false
server_properties_defaults: [] # allows for defaults to be set at the group level and overridden at the host level
server_properties: []

# Example item:
# - id: "123.123.123.123"
#   expires: "forever"
banned_ips: []

# Example item:
# - uuid: "0123abcd-01ab-23cd-45ef-012345abcdef"
#   name: "player_name"
#   expires: "forever"
banned_players: []

# Example item:
# - uuid: "0123abcd-01ab-23cd-45ef-012345abcdef"
#   name: "player_name"
#   level: 4
ops: []

# Example item:
# - uuid: "0123abcd-01ab-23cd-45ef-012345abcdef"
#   name: "player_name"
whitelist: []

# See files/opt/minecraft/config/paper-global.yml for example configuration.
paper_global_defaults: [] # intended to be used at the group level
paper_global: [] # intended to be used at the host level

# See files/opt/minecraft/config/paper-world-defaults.yml for example configuration.
paper_world_defaults: [] # intended to be used at the group level
paper_world: [] # intended to be used at the host level

# See files/opt/minecraft/bukkit.yml for example configuration.
bukkit_defaults: [] # intended to be used at the group level
bukkit: [] # intended to be used at the host level

# See files/opt/minecraft/spigot.yml for example configuration.
spigot_defaults: [] # intended to be used at the group level
spigot: [] # intended to be used at the host level

# See files/opt/minecraft/commands.yml for example configuration.
commands_defaults: [] # intended to be used at the group level
commands: [] # intended to be used at the host level