- import_tasks: hostname.yml
  become: true

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Install essential packages
  become: true
  ansible.builtin.apt:
    state: present
    package:
      # Ensure HTTPS APT sources support
      - apt-transport-https
      - ca-certificates
      # Enable auto-updates and notifications
      - unattended-upgrades
      - apt-listchanges
      # System tools
      - cron
      # Misc tools
      - curl
      - wget
      - htop
      - vim

- name: Remove unused packages
  become: true
  ansible.builtin.apt:
    autoremove: yes

- name: Clean apt cache
  become: true
  ansible.builtin.apt:
    autoclean: yes