---
- name: Retrieve and Encrypt Secrets from 1Password
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if signed into 1Password account
      ansible.builtin.command: op vault get {{ onepassword_vault }}
      register: op_signed_in
      ignore_errors: true

    - name: Sign into 1Password account if not signed in
      ansible.builtin.command: op signin your_signin_address --output=raw
      when: op_signed_in.rc != 0  # Sign in only if not signed in

    - name: Retrieve the secrets from 1Password
      set_fact:
        secrets_dict:
          ansible_user: "{{ lookup('community.general.onepassword', 'ansible-user', vault=onepassword_vault, field='username' ) }}"
          ansible_password: "{{ lookup('community.general.onepassword', 'ansible-user', vault=onepassword_vault, field='password' ) }}"
          ansible_public_key: "{{ lookup('community.general.onepassword', 'ansible-ssh', vault=onepassword_vault, field='public key' ) }}"
          ansible_private_key: "{{ lookup('community.general.onepassword', 'ansible-ssh', vault=onepassword_vault, field='private key' ) }}"
      no_log: true

    - name: Store the secrets in an ansible-vault
      copy:
        content: "{{ secrets_dict | to_nice_yaml }}"
        dest: ../group_vars/all/vault.yml

    - name: Encrypt the secrets
      ansible.builtin.command: ansible-vault encrypt ../group_vars/all/vault.yml --vault-password-file ../.ansible-vault-password