- hosts: gitlab
  roles:
    - common
    - gitlab
  tasks:
    - name: Create GitLab SSL certificate directory
      become: true
      ansible.builtin.file:
        path: /etc/gitlab/certs
        state: directory
        mode: '0755'
    - name: Create GitLab SSL certificate
      become: true
      ansible.builtin.copy:
        content: "{{ lookup('community.general.onepassword', 'int.jrtashjian.com', vault=onepassword_vault, field='certificate' ) }}"
        dest: /etc/gitlab/certs/fullchain.pem
        mode: '0644'
    - name: Create GitLab SSL certificate key
      become: true
      ansible.builtin.copy:
        content: "{{ lookup('community.general.onepassword', 'int.jrtashjian.com', vault=onepassword_vault, field='private_key' ) }}"
        dest: /etc/gitlab/certs/privkey.pem
        mode: '0644'

- hosts: gitlab-runner
  roles:
    - common
    - docker
    - gitlab-runner
  become: true