- hosts: gitlab
  roles:
    - role: ssl-certs
      ssl_cert_dir: /etc/gitlab/certs
    - common
    - gitlab
  become: true

- hosts: gitlab-runner
  roles:
    - role: ssl-certs
      ssl_cert_dir: /etc/gitlab-runner/certs
    - common
    - docker
    - gitlab-runner
  become: true

# Run this command on each runner to register it with GitLab:

# sudo gitlab-runner register --url https://gitlab.int.jrtashjian.com --non-interactive \
# --tls-ca-file /etc/gitlab-runner/certs/fullchain.pem \
# --executor "docker" \
# --docker-image alpine:latest \
# --template-config /tmp/config.toml \
# --token REPLACE_WITH_RUNNER_TOKEN