- hosts: proxmox
  roles:
    - proxmox
    - common

- hosts: docker
  roles:
    - docker

- hosts: minecraft-proxies
  roles:
    - common
    - minecraft-proxy

- hosts: minecraft-worlds
  roles:
    - common
    - minecraft-papermc

- hosts: gitlab
  roles:
    - common
    - certbot
    - gitlab