- hosts: proxmox
  roles:
    - proxmox
    - common

- hosts: cmangos
  roles:
    - common
    - docker

- hosts: docker
  roles:
    - docker

- hosts: minecraft-proxies
  roles:
    - common
    - minecraft-proxy

- hosts: minecraft-worlds
  roles:
    - common
    - minecraft-papermc

- hosts: gitlab
  roles:
    - common
    - certbot
    - gitlab

- hosts: ldap
  roles:
    - common
    - lldap
  pre_tasks:
    - name: Create SSL certificate directory
      ansible.builtin.file:
        path: /etc/lldap/certs
        state: directory
        mode: '0755'
    - name: Create SSL certificate
      ansible.builtin.copy:
        content: "{{ cluster_ssl_certificate }}"
        dest: /etc/lldap/certs/fullchain.pem
        mode: '0644'
    - name: Create SSL certificate key
      ansible.builtin.copy:
        content: "{{ cluster_ssl_certificate_key }}"
        dest: /etc/lldap/certs/privkey.pem
        mode: '0644'

- hosts: sso
  roles:
    - common
    - authelia
  pre_tasks:
    - name: Create SSL certificate directory
      ansible.builtin.file:
        path: /etc/authelia/certs
        state: directory
        mode: '0755'
    - name: Create SSL certificate
      ansible.builtin.copy:
        content: "{{ cluster_ssl_certificate }}"
        dest: /etc/authelia/certs/fullchain.pem
        mode: '0644'
    - name: Create SSL certificate key
      ansible.builtin.copy:
        content: "{{ cluster_ssl_certificate_key }}"
        dest: /etc/authelia/certs/privkey.pem
        mode: '0644'